### ISSUE TITLE
java.lang.ClassNotFoundException when initializing TimeZoneEngine in version 2018d.2

### ISSUE THREAD

**Issue by BohdanZhezlo** [RomanIakovlev/timeshape#2]
Hi, when initializing TimeZoneEngine from version 2018d.2 it throws ClassNotFoundException:

> Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/iakovlev/timeshape/proto/Geojson$Feature
at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:72)
at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:59)

It seems that protobuf code is not included in the distributable jar from Maven repo, but TimeZoneEngine depends on it.

**Comment by RomanIakovlev** [comment]
Hi, thanks for reporting this. You're probably right regarding the root cause, I'll look into it in the next days and let you know.

**Comment by florentgarin** [comment]
Yeah I confirm:
Failure to find net.iakovlev:protostuff:jar:2018d.2

This lib looks promising and a solve a real problem, any chance you could provide a fix?

Thanks.

**Comment by RomanIakovlev** [comment]
Thanks again for reporting this, I've published version `2018d.3` that fixes the problem. It should soon be available on Maven Central, give it a try!

**Comment by WingGithub** [comment]
I'm seeing this issue on 2018d.6
 Causing: java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
! at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:131)
! at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:116)

I have no idea why it happening in my project but it went away when I manually included the protobuf dependency in the pom.xml. The strange thing is this does not happen on a standalone test project.

**Comment by RomanIakovlev** [comment]
Ok, it's definitely a different root cause, but I'll reopen the issue to keep track of this.

**Comment by WingGithub** [comment]
Could it be my project has a transitive dependency on an older version of protobuf and if TimeZoneEngine depends on a newer version but does not specify that version, maven does not resolve the dependency correctly? Just a wild ass guess.

**Comment by Rookiee111** [comment]
I am also facing a similar issue, use version 6 
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/iakovlev/timeshape/proto/Geojson$Feature
  at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:131)
  at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:116)
  ... 54 elided
Caused by: java.lang.NoClassDefFoundError: net/iakovlev/timeshape/proto/Geojson$Feature
  ... 56 more
Caused by: java.lang.ClassNotFoundException: net.iakovlev.timeshape.proto.Geojson$Feature
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
  ... 56 more

is this a bug or something wrong with the dependency, please advise..

**Comment by RomanIakovlev** [comment]
@WingGithub that indeed looks like a binary incompatibility between different protobuf versions. Could you please tell which one do you use in your project?
@Rookiee111 could you please share more details about how your project is setup? Is it Android or Oracle/OpenJDK? Which build system are you using? Could you share a reproducible example, a project setup and code where this error happens?

**Comment by WingGithub** [comment]
@RomanIakovlev I think I finally found it: protobuf-java:2.6.1

**Comment by Rookiee111** [comment]
@romanlakovlev sorry for the delay in responding back .  I was able to figure it out, it was dependency issue which causing this .. I am integrating this with spark, however I had to use another approach as with timeshape the performance is very slow .. but thanks for responding back.. have a good day

**Comment by Rookiee111** [comment]
@romanlakovlev sorry for the delay in responding back .  I was able to figure it out, it was dependency issue which causing this .. I am integrating this with spark, however I had to use another approach as with timeshape the performance is very slow .. but thanks for responding back.. have a good day

**Comment by RomanIakovlev** [comment]
This issue has been open for a while without much activity. Recent release of Timeshape has upgraded protobuf-java to 3.10.0, and probably older problems are not relevant anymore. If something similar to this again comes up, please open another issue.

**Comment by erighet** [comment]
Hi! I'm using version 2022g.17 with java 17 and spring 3, and i'm getting this error agan:
`2023-06-03 22:15:11 ERROR i.g.m.service.impl.TrackServiceImpl:255 - net/iakovlev/timeshape/TimeZoneEngine
java.lang.NoClassDefFoundError: net/iakovlev/timeshape/TimeZoneEngine`

**Comment by RomanIakovlev** [comment]
This is also discussed here #122, with a suggested solution.
